### ISSUE TITLE
README proofreading, and a question

### ISSUE THREAD

**Issue by glaebhoerl** [lamdu/hypertypes#10]
I was re-reading the README to try to refresh my understanding, and noticed a couple of probable editing snafus:

 * At one point, there is the sentence: "Some extensions we use but would like to avoid (we're looking for alternative solutions but haven't found them):", but then there is nothing following the colon.

 * A bit further down, "one would have to declare an explicit expression type for each expression type for use as ...". Was a sentence fragment accidentally duplicated here? (If not, maybe it's just a bit confusing.)

---

And something I started wondering about: how does the `hypertypes` approach compare to the "HKD for nested structures" approach?

The only listed drawback of the latter is that `Rank2.Functor` doesn't work for it. Ok. (Could you write a separate class?) But apart from that...

```haskell
data Expr f
    = EVar Text
    | EApp (f (Expr f)) (f (Expr f))
    | ELam Text (f (Typ f)) (f (Expr f))

data Typ f
    = TInt
    | TFunc (f (Typ f)) (f (Typ f))
```

It does seem to handle mutual recursion fine (at least, as far as writing down the types). And the two seem kind of analogous in a way: in one case, you have `f` on the outer level and the recursive structure is again parameterized by `f`; and in the other, you have `h` on the outer level, which, internally, applies its parameter (e.g. `Expr`) to `h` again to achieve parameterization of the recursive structure.

If I were to hazard a very rough guess, maybe the HKD approach is fine as long as you only want to alter the shape in "regular" ways, in some sense, while `hypertypes` in addition lets you do fancy tricks with the underlying fixpoints...?

**Comment by yairchu** [comment]
> At one point, there is the sentence: "Some extensions we use but would like to avoid (we're looking for alternative solutions but haven't found them):", but then there is nothing following the colon.

Oh, yes that accidentally remained from when we've used `UndecidableSuperClasses`. Fixed now, thanks!

> And something I started wondering about: how does the hypertypes approach compare to the "HKD for nested structures" approach?
>
> The only listed drawback of the latter is that Rank2.Functor doesn't work for it. Ok. (Could you write a separate class?) But apart from that...
>
> ...
> If I were to hazard a very rough guess, maybe the HKD approach is fine as long as you only want to alter the shape in "regular" ways, in some sense, while hypertypes in addition lets you do fancy tricks with the underlying fixpoints...?

A few more simple examples of things that you can't do with "HKD for nested structures":

* [`hzip :: (h # p) -> (h # q) -> h # (p :*: q)`](https://hackage.haskell.org/package/hypertypes-0.1.0.2/docs/Hyper-Class-Apply.html). In addition to not being able to declare a type-class for it (which is the same issue as with `Rank2.Functor`), you can't even represent the result type because one can't have a fix point that contains two subexpressions each with a different fix-points.
* Use [`data Diff a b e = CommonSubTree (Ann (a :*: b) e) | CommonBody (CommonBody a b e) | Different ((Ann a :*: Ann b) e)`](https://hackage.haskell.org/package/hypertypes-0.1.0.2/docs/Hyper-Diff.html) as the parameter, another fix-point which can use different fix-points for the child nodes, 

Don't know whether those count as fancy tricks.

> A bit further down, "one would have to declare an explicit expression type for each expression type for use as ...". Was a sentence fragment accidentally duplicated here? (If not, maybe it's just a bit confusing.)

I'll look into whether I can word it better.

**Comment by yairchu** [comment]
> A bit further down, "one would have to declare an explicit expression type for each expression type for use as ...". Was a sentence fragment accidentally duplicated here? (If not, maybe it's just a bit confusing.)

I changed the wording now, is it better?

**Comment by glaebhoerl** [comment]
Yeah I think so!

> Don't know whether those count as fancy tricks.

This is the kind of thing I was suspecting might be the case yeah. (I don't know if "fancy tricks" is the right term either, it's just the one that came to mind.) Thanks for elaborating!

**Comment by yairchu** [comment]
Another way of describing it, is that just like we find ourselves needing mutually recursive AST types, we also sometimes find ourselves in the same situation with the fix-points. And this approach enables the same power for both.

**Comment by yairchu** [comment]
Another way of describing it, is that just like we find ourselves needing mutually recursive AST types, we also sometimes find ourselves in the same situation with the fix-points. And this approach enables the same power for both.
